### ISSUE TITLE
I don't understand how to control colorduino 

### ISSUE THREAD

**Issue by haasannata** [funnypolynomial/Chromaduino#4]
I have tried many libraries to control this, sometimes changing their content. But I didn't know how to control this.
I would appreciate it if you could tell me how I can control it.

![IMG_20221112_153411](https://user-images.githubusercontent.com/44571281/201461102-d307bbe8-1a18-442b-adbb-b13d3d0f9b71.jpg)
![IMG_20221112_153416](https://user-images.githubusercontent.com/44571281/201461103-a3c4e70b-b97b-431a-ad2b-90fd4a5311aa.jpg)

I am using ArduinoIDE ver2.0.1.
Please let me know if you need any information.
I hope you can help me.

**Comment by funnypolynomial** [comment]
The LED matrix is RGB? Common anode? 
You have flashed my Chromaduino sketch onto a Funduino/Colorduino board?
That looks a bit like a Funduino/Colorduino in the background with the alligator clip.  
What happens if you connect the two together directly, rather than via wires? It would not be hard to get the wires wrong!
Directly socketed, LED 1 should go to BLUE 1.
After 5s, the Chromaduino should run a demo if it has received no i2C instructions.
You need a **second** Arduino to drive/control the display, connected via I2C to the LED board.
ChromaduinoScrollDemoController.ino is an example sketch to run on the controlling Arduino.

You show two photos.  Are the LEDs changing?  I wonder if you're seeing the Chromaduino "idle" demo animation, but only the **red** component is working?  Because it's a red-only matrix or there's a wiring problem?

**Comment by haasannata** [comment]
sorry kind person
Because I'm an idiot, I was using cathode common.
I would like to know something about using a common cathode matrix if possible.

**Comment by funnypolynomial** [comment]
I'm surprised you got anything lighting up on a common cathode matrix.  
But in any case, the library (and probably the board) are designed for _common anode only_. 
So sorry, but I can't help.
