### ISSUE TITLE
Works without an external master.

### ISSUE THREAD

**Issue by haasannata** [funnypolynomial/Chromaduino#6]
I'm thinking of getting this to work without an external master.
To do that, we need to stop waiting for data to be sent by I2C and act as the master after the first Colorduino shows it on the display.
I would like you to create a code to control the display with Colorduino alone, or give me a hint for creating it.
If you give me a hint, I might be able to write the code.

Best regards

**Comment by funnypolynomial** [comment]
Not clear what you're trying to do.  _Perhaps_ you have more than one Colorduino and you want the first to drive the other(s), rather than having an additional Arduino driving them all?  Good luck. Not what this library is intended for so sorry, I won't be creating the code for you! 
As far as a hint goes, well the Chromaduino already creates its own graphics, see the #ifdef DEMO part at the bottom of Chromaduino.ino where the code writes RGB values to matrixDataA or matrixDataB.  I guess combine that with sending additional RGB data via I2C to a different matrix, with a different address, running standard Chromaduino? 
If you changed
`unsigned long demoTimeout = 5000UL; // wait 5s after startup with no balance command before running demo.`
to be 0, the demo would not wait for data.

**Comment by haasannata** [comment]
>>Not clear what you're trying to do. Perhaps you have more than one Colorduino and you want the first to drive the other(s), rather than having an additional Arduino driving them all?
yes,thats right
>> Good luck. Not what this library is intended for so sorry, I won't be creating the code for you!
Indeed it is. I'm sorry, but please bear with this nonsense a little more.

The simplest solution I can think of is to send the I2C communication data to the Colorduino itself that sent it. That way you can run multiple Colorduinos without an external Arduino without making any major changes to the Chromaduino firmware.

**Comment by funnypolynomial** [comment]
OK.
